# Generated by Django 6.0 on 2025-12-24 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0002_rename_name_player_first_name_player_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='thumbnails',
            field=models.ImageField(blank=True, null=True, upload_to='players/'),
        ),
    ]
