# Generated by Django 6.0 on 2026-01-08 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teamA', models.CharField(max_length=50)),
                ('teamB', models.CharField(max_length=50)),
                ('teamA_score', models.PositiveIntegerField(default=0)),
                ('teamB_score', models.PositiveIntegerField(default=0)),
                ('current_minute', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(default='scheduled', max_length=20)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
