# Generated by Django 6.0 on 2025-12-14 14:53

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('venue', models.CharField(max_length=200)),
                ('date', models.DateTimeField()),
                ('capacity', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='TicketTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('vip', 'Vip'), ('Regular', 'Regular'), ('students', 'Students')], default='Regular', max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_available', models.PositiveIntegerField()),
                ('seat_section', models.CharField(blank=True, max_length=50, null=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket_types', to='tickets.event')),
            ],
        ),
        migrations.CreateModel(
            name='PurchasedTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_code', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('status', models.CharField(choices=[('confirmed', 'Confirmed'), ('used', 'Used'), ('cancelled', 'Cancelled')], default='confirmed', max_length=20)),
                ('purchased_at', models.DateTimeField(auto_now_add=True)),
                ('buyer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchased_tickets', to='tickets.tickettemplate')),
            ],
        ),
    ]
