# Generated by Django 6.0 on 2025-12-19 14:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_alter_tickettemplate_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tickettemplate',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket_types', to='tickets.event'),
        ),
    ]
