# Generated by Django 6.0 on 2025-12-19 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0004_event_created_at_event_slug_event_team_a_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='capacity',
        ),
        migrations.AlterField(
            model_name='tickettemplate',
            name='name',
            field=models.CharField(choices=[('VIP', 'Vip'), ('Regular', 'Regular'), ('Students', 'Students')], default='Regular', max_length=100),
        ),
    ]
