# Generated by Django 6.0 on 2025-12-22 10:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0005_remove_event_capacity_alter_tickettemplate_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchasedticket',
            name='buyer',
            field=models.CharField(default=datetime.datetime(2025, 12, 22, 10, 54, 36, 344097, tzinfo=datetime.timezone.utc), max_length=100),
            preserve_default=False,
        ),
    ]
